[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --no-input"
]

[phases.deploy]
cmds = [
  "python manage.py migrate --no-input",
  "python manage.py load_fixtures"
]

[start]
cmd = "gunicorn config.wsgi --workers 2 --bind 0.0.0.0:$PORT"
