# Generated by Django 6.0.5 on 2026-05-21 21:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид оборудования')),
                ('icon', models.CharField(default='monitor', max_length=50, verbose_name='Иконка (lucide)')),
            ],
            options={
                'verbose_name': 'Вид оборудования',
                'verbose_name_plural': 'Виды оборудования',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('specs', models.TextField(blank=True, verbose_name='Технические характеристики')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('condition', models.CharField(choices=[('ok', 'Исправно'), ('broken', 'Неисправно'), ('repair', 'В ремонте'), ('written_off', 'Списано')], default='ok', max_length=20, verbose_name='Состояние')),
                ('is_present', models.BooleanField(default=True, verbose_name='На месте')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Дата внесения')),
                ('last_check_date', models.DateField(blank=True, null=True, verbose_name='Последняя дата проверки')),
                ('next_check_date', models.DateField(blank=True, null=True, verbose_name='Следующая дата проверки')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость (руб.)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_created', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='core.room', verbose_name='Кабинет')),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='equipment.equipmenttype', verbose_name='Вид оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['reg_number'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='equipment/gallery/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Фото оборудования',
                'verbose_name_plural': 'Фото оборудования',
            },
        ),
        migrations.CreateModel(
            name='WriteOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина списания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_word', models.CharField(blank=True, max_length=20)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoffs_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoffs_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeoffs', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Акт списания',
                'verbose_name_plural': 'Акты списания',
            },
        ),
    ]
