# Generated by Django 6.0.5 on 2026-05-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название отчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Параметры фильтрации')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл отчёта')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
    ]
